#-------------------------------------------------------------------------------------------
# Copyright (c) 2024-present, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------
set(SOURCES
        src/main.cpp
        src/camera.cpp
        src/editor_engine.cpp
        src/engine.cpp
        src/engine_loop.cpp
        src/game_engine.cpp
        src/input.cpp
        src/core/filesystem.cpp
        src/core/job_system.cpp
        src/core/logger.cpp
        src/core/string.cpp
        src/rendering/material.cpp
        src/rendering/mesh.cpp
        src/rendering/renderable.cpp
        src/rendering/renderer.cpp
        src/rendering/scene.cpp
        src/rendering/render_passes/grid_pass.cpp
        src/rendering/render_passes/opaque_pass.cpp
        src/rhi/buffer.cpp
        src/rhi/command_list.cpp
        src/rhi/compute_pass.cpp
        src/rhi/compute_pipeline.cpp
        src/rhi/descriptor_manager.cpp
        src/rhi/graphics_device.cpp
        src/rhi/pipeline_layout.cpp
        src/rhi/render_pass.cpp
        src/rhi/render_pipeline.cpp
        src/rhi/resource_handle.cpp
        src/rhi/sampler.cpp
        src/rhi/shader_compiler.cpp
        src/rhi/shader_module.cpp
        src/rhi/surface.cpp
        src/rhi/texture.cpp
        src/rhi/texture_view.cpp
        src/rhi/vulkan/vulkan_buffer.cpp
        src/rhi/vulkan/vulkan_command_list.cpp
        src/rhi/vulkan/vulkan_compute_pass.cpp
        src/rhi/vulkan/vulkan_compute_pipeline.cpp
        src/rhi/vulkan/vulkan_descriptor_manager.cpp
        src/rhi/vulkan/vulkan_graphics_device.cpp
        src/rhi/vulkan/vulkan_pipeline_layout.cpp
        src/rhi/vulkan/vulkan_render_pass.cpp
        src/rhi/vulkan/vulkan_render_pipeline.cpp
        src/rhi/vulkan/vulkan_sampler.cpp
        src/rhi/vulkan/vulkan_shader_module.cpp
        src/rhi/vulkan/vulkan_surface.cpp
        src/rhi/vulkan/vulkan_texture.cpp
        src/rhi/vulkan/vulkan_texture_view.cpp
        src/windowing/key_events.cpp
        src/windowing/mouse_events.cpp
        src/windowing/window.cpp
        src/windowing/window_events.cpp)

set(HEADERS
        include/camera.hpp
        include/editor_engine.hpp
        include/engine.hpp
        include/engine_loop.hpp
        include/game_engine.hpp
        include/input.hpp
        include/core/assertion.hpp
        include/core/bit_flags.hpp
        include/core/bits.hpp
        include/core/filesystem.hpp
        include/core/job_system.hpp
        include/core/logger.hpp
        include/core/prerequisites.hpp
        include/core/string.hpp
        include/core/thread_safe_ring_buffer.hpp
        include/rendering/camera.hpp
        include/rendering/material.hpp
        include/rendering/mesh.hpp
        include/rendering/renderable.hpp
        include/rendering/renderer.hpp
        include/rendering/scene.hpp
        include/rendering/render_passes/grid_pass.hpp
        include/rendering/render_passes/opaque_pass.hpp
        include/rhi/buffer.hpp
        include/rhi/command_list.hpp
        include/rhi/compare_operation.hpp
        include/rhi/compute_pass.hpp
        include/rhi/compute_pipeline.hpp
        include/rhi/descriptor_manager.hpp
        include/rhi/dimension.hpp
        include/rhi/format.hpp
        include/rhi/graphics_device.hpp
        include/rhi/pipeline_layout.hpp
        include/rhi/render_pass.hpp
        include/rhi/render_pipeline.hpp
        include/rhi/resource_handle.hpp
        include/rhi/sampler.hpp
        include/rhi/shader_module.hpp
        include/rhi/shader_compiler.hpp
        include/rhi/shader_type.hpp
        include/rhi/subresource_range.hpp
        include/rhi/surface.hpp
        include/rhi/texture.hpp
        include/rhi/texture_view.hpp
        include/rhi/vulkan/vulkan_buffer.hpp
        include/rhi/vulkan/vulkan_command_list.hpp
        include/rhi/vulkan/vulkan_common.hpp
        include/rhi/vulkan/vulkan_compute_pass.hpp
        include/rhi/vulkan/vulkan_compute_pipeline.hpp
        include/rhi/vulkan/vulkan_descriptor_manager.hpp
        include/rhi/vulkan/vulkan_graphics_device.hpp
        include/rhi/vulkan/vulkan_pipeline_layout.hpp
        include/rhi/vulkan/vulkan_render_pass.hpp
        include/rhi/vulkan/vulkan_render_pipeline.hpp
        include/rhi/vulkan/vulkan_sampler.hpp
        include/rhi/vulkan/vulkan_shader_module.hpp
        include/rhi/vulkan/vulkan_surface.hpp
        include/rhi/vulkan/vulkan_texture.hpp
        include/rhi/vulkan/vulkan_texture_view.hpp
        include/windowing/event.hpp
        include/windowing/key_codes.hpp
        include/windowing/key_events.hpp
        include/windowing/mouse_codes.hpp
        include/windowing/mouse_events.hpp
        include/windowing/window.hpp
        include/windowing/window_events.hpp)

if (WIN32)
    set(SOURCES
            ${SOURCES})

    set(HEADERS
            ${HEADERS}
            include/rhi/d3d12/d3d12_common.hpp)
endif ()

hyperengine_define_executable(hyper_engine)
target_link_libraries(
        hyper_engine
        PRIVATE
        argparse
        EnTT::EnTT
        fastgltf
        fmt
        glm
        libassert::assert
        imgui
        spdlog
        stb
        DirectXShaderCompiler
        SDL3::SDL3
        volk
        VulkanMemoryAllocator)
if (WIN32)
    target_link_libraries(
            hyper_engine
            PUBLIC
            d3d12.lib
            dxgi.lib
            D3D12MemoryAllocator)
endif ()

target_compile_definitions(
        hyper_engine
        PUBLIC
        -DGLM_FORCE_RADIANS
        -DGLM_FORCE_DEPTH_ZERO_TO_ONE)
target_include_directories(
        hyper_engine
        PRIVATE
        ${CMAKE_SOURCE_DIR}/assets/shaders)
