/*
 * Copyright (c) 2023, SkillerRaptor
 *
 * SPDX-License-Identifier: MIT
 */

use winit::event::VirtualKeyCode;

#[derive(Clone, Copy, Debug)]
pub enum KeyCode {
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    Key0,

    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    Escape,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,

    Snapshot,
    Scroll,
    Pause,

    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,

    Left,
    Up,
    Right,
    Down,

    Backspace,
    Return,
    Space,

    Compose,

    Caret,

    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadDivide,
    NumpadDecimal,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    NumpadMultiply,
    NumpadSubtract,

    AbntC1,
    AbntC2,
    Apostrophe,
    Apps,
    Asterisk,
    At,
    Ax,
    Backslash,
    Calculator,
    Capital,
    Colon,
    Comma,
    Convert,
    Equals,
    Grave,
    Kana,
    Kanji,
    LAlt,
    LBracket,
    LControl,
    LShift,
    LWin,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    Mute,
    MyComputer,
    NavigateForward,
    NavigateBackward,
    NextTrack,
    NoConvert,
    OEM102,
    Period,
    PlayPause,
    Plus,
    Power,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    RShift,
    RWin,
    Semicolon,
    Slash,
    Sleep,
    Stop,
    Sysrq,
    Tab,
    Underline,
    Unlabeled,
    VolumeDown,
    VolumeUp,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Yen,
    Copy,
    Paste,
    Cut,
}

impl From<VirtualKeyCode> for KeyCode {
    fn from(value: VirtualKeyCode) -> Self {
        match value {
            VirtualKeyCode::Key1 => Self::Key1,
            VirtualKeyCode::Key2 => Self::Key2,
            VirtualKeyCode::Key3 => Self::Key3,
            VirtualKeyCode::Key4 => Self::Key4,
            VirtualKeyCode::Key5 => Self::Key5,
            VirtualKeyCode::Key6 => Self::Key6,
            VirtualKeyCode::Key7 => Self::Key7,
            VirtualKeyCode::Key8 => Self::Key8,
            VirtualKeyCode::Key9 => Self::Key9,
            VirtualKeyCode::Key0 => Self::Key0,
            VirtualKeyCode::A => Self::A,
            VirtualKeyCode::B => Self::B,
            VirtualKeyCode::C => Self::C,
            VirtualKeyCode::D => Self::D,
            VirtualKeyCode::E => Self::E,
            VirtualKeyCode::F => Self::F,
            VirtualKeyCode::G => Self::G,
            VirtualKeyCode::H => Self::H,
            VirtualKeyCode::I => Self::I,
            VirtualKeyCode::J => Self::J,
            VirtualKeyCode::K => Self::K,
            VirtualKeyCode::L => Self::L,
            VirtualKeyCode::M => Self::M,
            VirtualKeyCode::N => Self::N,
            VirtualKeyCode::O => Self::O,
            VirtualKeyCode::P => Self::P,
            VirtualKeyCode::Q => Self::Q,
            VirtualKeyCode::R => Self::R,
            VirtualKeyCode::S => Self::S,
            VirtualKeyCode::T => Self::T,
            VirtualKeyCode::U => Self::U,
            VirtualKeyCode::V => Self::V,
            VirtualKeyCode::W => Self::W,
            VirtualKeyCode::X => Self::X,
            VirtualKeyCode::Y => Self::Y,
            VirtualKeyCode::Z => Self::Z,
            VirtualKeyCode::Escape => Self::Escape,
            VirtualKeyCode::F1 => Self::F1,
            VirtualKeyCode::F2 => Self::F2,
            VirtualKeyCode::F3 => Self::F3,
            VirtualKeyCode::F4 => Self::F4,
            VirtualKeyCode::F5 => Self::F5,
            VirtualKeyCode::F6 => Self::F6,
            VirtualKeyCode::F7 => Self::F7,
            VirtualKeyCode::F8 => Self::F8,
            VirtualKeyCode::F9 => Self::F9,
            VirtualKeyCode::F10 => Self::F10,
            VirtualKeyCode::F11 => Self::F11,
            VirtualKeyCode::F12 => Self::F12,
            VirtualKeyCode::F13 => Self::F13,
            VirtualKeyCode::F14 => Self::F14,
            VirtualKeyCode::F15 => Self::F15,
            VirtualKeyCode::F16 => Self::F16,
            VirtualKeyCode::F17 => Self::F17,
            VirtualKeyCode::F18 => Self::F18,
            VirtualKeyCode::F19 => Self::F19,
            VirtualKeyCode::F20 => Self::F20,
            VirtualKeyCode::F21 => Self::F21,
            VirtualKeyCode::F22 => Self::F22,
            VirtualKeyCode::F23 => Self::F23,
            VirtualKeyCode::F24 => Self::F24,
            VirtualKeyCode::Snapshot => Self::Snapshot,
            VirtualKeyCode::Scroll => Self::Scroll,
            VirtualKeyCode::Pause => Self::Pause,
            VirtualKeyCode::Insert => Self::Insert,
            VirtualKeyCode::Home => Self::Home,
            VirtualKeyCode::Delete => Self::Delete,
            VirtualKeyCode::End => Self::End,
            VirtualKeyCode::PageDown => Self::PageDown,
            VirtualKeyCode::PageUp => Self::PageUp,
            VirtualKeyCode::Left => Self::Left,
            VirtualKeyCode::Up => Self::Up,
            VirtualKeyCode::Right => Self::Right,
            VirtualKeyCode::Down => Self::Down,
            VirtualKeyCode::Back => Self::Backspace,
            VirtualKeyCode::Return => Self::Return,
            VirtualKeyCode::Space => Self::Space,
            VirtualKeyCode::Compose => Self::Compose,
            VirtualKeyCode::Caret => Self::Caret,
            VirtualKeyCode::Numlock => Self::Numlock,
            VirtualKeyCode::Numpad0 => Self::Numpad0,
            VirtualKeyCode::Numpad1 => Self::Numpad1,
            VirtualKeyCode::Numpad2 => Self::Numpad2,
            VirtualKeyCode::Numpad3 => Self::Numpad3,
            VirtualKeyCode::Numpad4 => Self::Numpad4,
            VirtualKeyCode::Numpad5 => Self::Numpad5,
            VirtualKeyCode::Numpad6 => Self::Numpad6,
            VirtualKeyCode::Numpad7 => Self::Numpad7,
            VirtualKeyCode::Numpad8 => Self::Numpad8,
            VirtualKeyCode::Numpad9 => Self::Numpad9,
            VirtualKeyCode::NumpadAdd => Self::NumpadAdd,
            VirtualKeyCode::NumpadDivide => Self::NumpadDivide,
            VirtualKeyCode::NumpadDecimal => Self::NumpadDecimal,
            VirtualKeyCode::NumpadComma => Self::NumpadComma,
            VirtualKeyCode::NumpadEnter => Self::NumpadEnter,
            VirtualKeyCode::NumpadEquals => Self::NumpadEquals,
            VirtualKeyCode::NumpadMultiply => Self::NumpadMultiply,
            VirtualKeyCode::NumpadSubtract => Self::NumpadSubtract,
            VirtualKeyCode::AbntC1 => Self::AbntC1,
            VirtualKeyCode::AbntC2 => Self::AbntC2,
            VirtualKeyCode::Apostrophe => Self::Apostrophe,
            VirtualKeyCode::Apps => Self::Apps,
            VirtualKeyCode::Asterisk => Self::Asterisk,
            VirtualKeyCode::At => Self::At,
            VirtualKeyCode::Ax => Self::Ax,
            VirtualKeyCode::Backslash => Self::Backslash,
            VirtualKeyCode::Calculator => Self::Calculator,
            VirtualKeyCode::Capital => Self::Capital,
            VirtualKeyCode::Colon => Self::Colon,
            VirtualKeyCode::Comma => Self::Comma,
            VirtualKeyCode::Convert => Self::Convert,
            VirtualKeyCode::Equals => Self::Equals,
            VirtualKeyCode::Grave => Self::Grave,
            VirtualKeyCode::Kana => Self::Kana,
            VirtualKeyCode::Kanji => Self::Kanji,
            VirtualKeyCode::LAlt => Self::LAlt,
            VirtualKeyCode::LBracket => Self::LBracket,
            VirtualKeyCode::LControl => Self::LControl,
            VirtualKeyCode::LShift => Self::LShift,
            VirtualKeyCode::LWin => Self::LWin,
            VirtualKeyCode::Mail => Self::Mail,
            VirtualKeyCode::MediaSelect => Self::MediaSelect,
            VirtualKeyCode::MediaStop => Self::MediaStop,
            VirtualKeyCode::Minus => Self::Minus,
            VirtualKeyCode::Mute => Self::Mute,
            VirtualKeyCode::MyComputer => Self::MyComputer,
            VirtualKeyCode::NavigateForward => Self::NavigateForward,
            VirtualKeyCode::NavigateBackward => Self::NavigateBackward,
            VirtualKeyCode::NextTrack => Self::NextTrack,
            VirtualKeyCode::NoConvert => Self::NoConvert,
            VirtualKeyCode::OEM102 => Self::OEM102,
            VirtualKeyCode::Period => Self::Period,
            VirtualKeyCode::PlayPause => Self::PlayPause,
            VirtualKeyCode::Plus => Self::Plus,
            VirtualKeyCode::Power => Self::Power,
            VirtualKeyCode::PrevTrack => Self::PrevTrack,
            VirtualKeyCode::RAlt => Self::RAlt,
            VirtualKeyCode::RBracket => Self::RBracket,
            VirtualKeyCode::RControl => Self::RControl,
            VirtualKeyCode::RShift => Self::RShift,
            VirtualKeyCode::RWin => Self::RWin,
            VirtualKeyCode::Semicolon => Self::Semicolon,
            VirtualKeyCode::Slash => Self::Slash,
            VirtualKeyCode::Sleep => Self::Sleep,
            VirtualKeyCode::Stop => Self::Stop,
            VirtualKeyCode::Sysrq => Self::Sysrq,
            VirtualKeyCode::Tab => Self::Tab,
            VirtualKeyCode::Underline => Self::Underline,
            VirtualKeyCode::Unlabeled => Self::Unlabeled,
            VirtualKeyCode::VolumeDown => Self::VolumeDown,
            VirtualKeyCode::VolumeUp => Self::VolumeUp,
            VirtualKeyCode::Wake => Self::Wake,
            VirtualKeyCode::WebBack => Self::WebBack,
            VirtualKeyCode::WebFavorites => Self::WebFavorites,
            VirtualKeyCode::WebForward => Self::WebForward,
            VirtualKeyCode::WebHome => Self::WebHome,
            VirtualKeyCode::WebRefresh => Self::WebRefresh,
            VirtualKeyCode::WebSearch => Self::WebSearch,
            VirtualKeyCode::WebStop => Self::WebStop,
            VirtualKeyCode::Yen => Self::Yen,
            VirtualKeyCode::Copy => Self::Copy,
            VirtualKeyCode::Paste => Self::Paste,
            VirtualKeyCode::Cut => Self::Cut,
        }
    }
}
