name: 'setup_cache'

inputs:
  compiler:
    required: true
    type: string
  build_type:
    required: true
    type: string
  generator:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.ccache
        key: ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}-${{ inputs.generator }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}
