name: build

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build:
    name: ${{matrix.os}} ${{matrix.compiler}} ${{matrix.build_type}}
    runs-on: ${{ matrix.os }}
    env:
      vulkan_version: "1.4.341.1"
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        compiler:
          - llvm
          - gcc
        build_type:
          - Release
          - Debug
        generator:
          - "Ninja Multi-Config"
        exclude:
          - os: windows-latest
            compiler: gcc
        include:
          - os: windows-latest
            compiler: msvc
            generator: "Visual Studio 17 2022"
            build_type: Debug
          - os: windows-latest
            compiler: msvc
            generator: "Visual Studio 17 2022"
            build_type: Release
    steps:
      - uses: actions/checkout@v6

      - name: Setup Cache
        uses: ./.github/actions/setup_cache
        with:
          compiler: ${{ matrix.compiler }}
          build_type: ${{ matrix.build_type }}
          generator: ${{ matrix.generator }}

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true
          ccache: true

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: ${{ env.vulkan_version }}
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true

      - name: Configure CMake
        run: |
          cmake -S . -B ./build -G "${{ matrix.generator }}" -DCMAKE_BUILD_TYPE:STRING=${{ matrix.build_type }}

      - name: Build
        run: |
          cmake --build ./build --config ${{ matrix.build_type }}

      - name: Unix - Test
        if: runner.os != 'Windows'
        working-directory: ./build
        run: |
          ctest -C ${{ matrix.build_type }}

      - name: Windows - Test
        if: runner.os == 'Windows'
        working-directory: ./build
        run: |
          ctest -C ${{ matrix.build_type }}

      - name: Unix - Prepare upload
        if: runner.os != 'Windows'
        run: |
          tar cfz ${{ matrix.config.artifact }} build

      - name: Windows - Prepare upload
        if: runner.os == 'Windows'
        run: |
          7z a -tzip ${{ matrix.config.artifact }} build/*

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ${{ matrix.config.artifact }}
          name: ${{ matrix.config.artifact }}