name: build

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build:
    name: ${{matrix.os}} ${{matrix.compiler}} ${{matrix.build_type}}
    runs-on: ${{ matrix.os }}
    env:
      SCCACHE_GHA_ENABLED: "true"
      SCCACHE_IGNORE_SERVER_IO_ERROR: 1
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        compiler:
          - llvm
          - gcc
          - msvc
        build_type:
          - Release
          - Debug
        generator:
          - "Ninja"
        exclude:
          - os: ubuntu-latest
            compiler: msvc
          - os: windows-latest
            compiler: gcc
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          autocrlf: false

      - name: Update environment
        if: runner.os != 'Windows'
        run: |
          sudo apt update -qq
          sudo apt install -y \
            libgl1-mesa-dev \
            xorg-dev

      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.cpm-cache
          key: ${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.build_type }}

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true

      - name: Prepare Vulkan SDK
        uses: humbletim/install-vulkan-sdk@033219e2d69dd4d3e873e217eb385fdd4b4438f4
        with:
          version: latest
          cache: true

      - name: Configure CMake
        run: |
          cmake -S . -B ./build -G "${{ matrix.generator }}" -DHE_ENABLE_CACHE=ON -DCPM_SOURCE_CACHE="${{ github.workspace }}/.cpm-cache" -DCMAKE_BUILD_TYPE:STRING=${{ matrix.build_type }}

      - name: Build
        run: |
          cmake --build ./build --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ./build
        run: |
          ctest -C ${{ matrix.build_type }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os == 'Windows' && 'windows' || 'linux' }}-${{ matrix.compiler }}-${{ matrix.build_type == 'Debug' && 'debug' || 'release' }}
          path: build/